### PR TITLE
add message body size limits in frontend and backend

### PR DESCRIPTION
**Pull request by zenkovev**

### CODE REVIEW

**Comment by zenkovev** [comment]
Refers to https://github.com/jackc/pgx/issues/2139

**Comment by zenkovev** [comment]
Thanks for the reply. Regarding the control over the frontend creation, yes, it's fair, then global atomics are really not needed. There remains control over the length of the frontend message at the structure level - PR has been updated.

**Comment by jackc** [comment]
The Frontend changes look okay. Seem to be just porting the existing system from the backend. But I'm not sure why there are any changes on Backend.

Also, the comment style of having the comments below the field instead of above or beside looks odd to me (Frontend.maxBodyLen).

**Comment by zenkovev** [comment]
I fixed the comments. About the changes in the Backend: there is one change transferred from the Frontend, checking that a positive number is set in `b.bodyLen`, that is, that the specified length of the message is correct.

**Comment by jackc** [comment]
👍

**Pull request merged**
