### PR TITLE
Register pgx driver using major version

### PR DESCRIPTION
**Pull request by mcdoker18**
Fixed: #1480

### CODE REVIEW

**Comment by jackc** [comment]
LGTM

**Comment by nhatthm** [comment]
And this will panic

```go
package main_test

import (
	"testing"

	_ "github.com/jackc/pgx/v4/stdlib"
	_ "github.com/jackc/pgx/v5/stdlib"
)

func TestImport(t *testing.T) {
	t.Parallel()
}
```

```
panic: sql: Register called twice for driver pgx

goroutine 1 [running]:
database/sql.Register({0x1042aff2e, 0x3}, {0x104360f58, 0x1400000e348})
	/go/libexec/src/database/sql/sql.go:51 +0x130
github.com/jackc/pgx/v5/stdlib.init.0()
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.3.0/stdlib/sql.go:93 +0xbc

Process finished with the exit code 1
```

**Comment by jackc** [comment]
Are you running with `v4.18.0` and `v5.3.0`?

**Comment by nhatthm** [comment]
> Are you running with `v4.18.0` and `v5.3.0`?

Yes

**Comment by nhatthm** [comment]
@jackc It works if I change the logic from 

```go
	drivers := sql.Drivers()
	// if pgx driver was already registered by different pgx major version then we skip registration under the default name.
	if i := sort.SearchStrings(sql.Drivers(), "pgx"); len(drivers) >= i || drivers[i] != "pgx" {
		sql.Register("pgx", pgxDriver)
	}
```

to

```go
	drivers := sql.Drivers()
	// if pgx driver was already registered by different pgx major version then we skip registration under the default name.
	if i := sort.SearchStrings(sql.Drivers(), "pgx"); len(drivers) == i || drivers[i] != "pgx" {
		sql.Register("pgx", pgxDriver)
	}
```

The only change is `len(drivers) >= i` => `len(drivers) == i`

If you are ok with this, I will create a PR

Here are the test cases

```go
package main_test

import (
	"sort"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestRegisterLogic(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		scenario string
		drivers  []string
		expected bool
	}{
		{
			scenario: "no drivers",
			drivers:  []string{},
			expected: true,
		},
		{
			scenario: "only v5",
			drivers:  []string{"pgx/v5"},
			expected: true,
		},
		{
			scenario: "others",
			drivers:  []string{"mysql", "sqlite3", "mssql"},
			expected: true,
		},
		{
			scenario: "has only pgx",
			drivers:  []string{"pgx"},
			expected: false,
		},
		{
			scenario: "has both pgx and pgx/v4",
			drivers:  []string{"pgx", "pgx/v4"},
			expected: false,
		},
		{
			scenario: "mixed, pgx is in the middle",
			drivers:  []string{"mysql", "sqlite3", "pgx", "pgx/v4", "mssql"},
			expected: false,
		},
		{
			scenario: "mixed, pgx is the head",
			drivers:  []string{"pgx", "pgx/v4", "mysql", "sqlite3", "mssql"},
			expected: false,
		},
		{
			scenario: "mixed, pgx is the tail",
			drivers:  []string{"mysql", "sqlite3", "mssql", "pgx"},
			expected: false,
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.scenario, func(t *testing.T) {
			t.Parallel()

			sort.Strings(tc.drivers)

			i := sort.SearchStrings(tc.drivers, "pgx")
			shouldRegister := len(tc.drivers) == i || tc.drivers[i] != "pgx"

			assert.Equal(t, tc.expected, shouldRegister)
		})
	}
}
```

**Pull request merged**
