### PR TITLE
Lazy load the inet constants

### PR DESCRIPTION
**Pull request by j16r**
This is a small change to the connection routine to lazy load the inet
constants to optimize the connection time slightly.

### CODE REVIEW

**Comment by j16r** [comment]
This breaks a lot, might need a rethink.

**Comment by jackc** [comment]
If we want to do this I think the proper place would be in Prepare. It would have to check the argument types and returned column types and see if a inet or cidr was among them, if so it could do the load. That said, I wonder if the connection time improvement is worth the additional complexity.

**Comment by j16r** [comment]
Trying something new in most recent commit - thoughts?

I agree the prepare idea seems to add a little bit of complexity, so I think this design is a little simpler.

**Comment by jackc** [comment]
What happens if the connection is not established through a ConnPool?

**Comment by j16r** [comment]
If you choose not to use a connection pool, you get the old behavior - it loads the values each time.

**Comment by jackc** [comment]
That makes sense, somehow I missed that when I looked at the code the first time. I agree we might want to tweak the interface for the shared objects at some point in the future, but it doesn't expose any public interface, so it can easily be changed when and if necessary.

I did make a couple of changes. First, sharing the PgTypes map between connections potentially allows a race condition, because that map is writable on a per connection basis (not that it is a good idea when using a connection pool -- but it is exposed). So instead of sharing the map it is copied to each connection.

I did the same for for the inet constants even though they aren't publicly exposed -- it just felt cleaner not to share memory between connections.

Thanks!

**Pull request merged**
