### PR TITLE
Implement 'MultiTracer'

### PR DESCRIPTION
**Pull request by EpicStep**
Hi. I'm tried to implement multi tracer (https://github.com/jackc/pgx/discussions/1677)
I took the fact that in ConnConfig the main tracer is QueryTracer and I decided to split from it into different tracers inside the constructor. If the API is good, I'll write the tests.

### CODE REVIEW

**Comment by jackc** [comment]
Seems reasonable.

**Comment by EpicStep** [comment]
Should we support pgxpool Acquire/Release Tracer at MultiTracer?

**Comment by jackc** [comment]
> Should we support pgxpool Acquire/Release Tracer?

Yes.

**Comment by EpicStep** [comment]
I'm done. I moved multi tracer to a separate package to avoid an import cycle.

**Pull request merged**
