### PR TITLE
Support CrateDB

### PR DESCRIPTION
**Pull request by felixge**
See https://github.com/jackc/pgx/issues/320

@jackc I spend a decent amount of time trying to come up with a minimally invasive patch and added some detailed in-line comments explaining my approach. Let me know what you think.

### CODE REVIEW

**Comment by jackc** [comment]
Thanks! Looks like as clean and narrow a change as we could hope for.

**Comment by felixge** [comment]
Thanks a lot! I'll be around to help if anybody runs into any unexpected issues with this.

**Comment by mfussenegger** [comment]
Nice to see CrateDB support in pgx.

One question to the `pg_type` query: Would it be possible to change this in
`pgx` to query explicitly on `pg_catalog.pg_type`?
I'm not sure if this could break anything with older postgres versions. Afaik
9+ should be fine.

It would be fairly simple for us to add the `typtype` column, but extending the
schema lookup logic is a bit more work.

The reason I'm asking is that this way we could add `typtype` and then no
longer have to worry about breaking anything here if we change something with
the error codes / error messages.

**Comment by felixge** [comment]
@mfussenegger not sure about @jackc, but from my POV changing the query to explicitly target the pg_catalog schema should be a reasonable change. As far as I can tell the pg_catalog schema has been around and can be explicitly specified in queries since at least [Postgres 7.3](https://www.postgresql.org/docs/7.3/static/ddl-schemas.html#AEN2160).

That being said, I think the workaround code should probably still need to stay in place to support older CrateDB versions for a while.

**Comment by jackc** [comment]
No objections from me for explicitly qualifying the `pg_catalog` schema.

**Comment by felixge** [comment]
@mfussenegger let me know when `typtype` gets implemented in CrateDB (is there a GH issue to subscribe to?). Then I'll do the PR and testing for pgx.

**Comment by mfussenegger** [comment]
@felixge We've added the column (see https://github.com/crate/crate/pull/6582) - will be part of 2.3 (or in the nightly builds starting tomorrow)

**Comment by felixge** [comment]
@mfussenegger cool. I'm traveling for the next three weeks, but I'll try to find some time to make a PR for this ASAP.

**Pull request merged**
