### PR TITLE
Add pgx pool acquire tracer

### PR DESCRIPTION
**Pull request by ngavinsir**
resolves https://github.com/jackc/pgx/issues/1747

### CODE REVIEW

**Comment by jackc** [comment]
Looks pretty good, but I have a few suggestions.

I think that `TraceAcquireStart` and `TraceAcquireEnd` should receive the `*Pool` as an argument. This would match the precedent set by `QueryTracer` of passing the item that is being traced. This would also mean that `TraceAcquireStartData` would not need to include `ConnConfig`. `TraceAcquireStartData` would still exist for possible future changes, but it would be empty.

It's a little confusing at first whether `TraceAcquireEnd` is called when the connection is acquired or when the acquisition is complete (i.e. when it is released). I think the docs should make that clearer. `TraceAcquireEndData` should probably also  include the `*pgx.Conn`.

---

This might be a separate feature, but it might also make sense to have a `ReleaseTracer` interface to allow tracing the entire time the the connection is acquired. In addition to the normal metrics usage of tracing, this would allow building diagnostics that would make it easier to track down connection leaks.

**Comment by ngavinsir** [comment]
@jackc updated, but not sure how to pass the current context to the release method, so it won't have the same parent trace as the acquire one

**Comment by jackc** [comment]
@ngavinsir I guess the release tracer is a bit trickier than I thought.

It is, perhaps, a little weird to use the context from Acquire for the Release. But I suppose context is where things like opentelemetry are stored so it is necessary. 🤔 At least it should be documented that it is the Acquire Context and/or made part of `TraceRelease(Start|End)Data`. Storing it in the `pgxpool.Conn` is fine. It's private so we can refactor it if necessary.

I also wonder if release tracing needs Start and End. Release should be consistently extremely fast and non-blocking. Perhaps it only needs one hook?

**Comment by jackc** [comment]
🤔 And on even further reflection, maybe the release tracer doesn't need context at all. As of 6f0deff0156a7ffcd557eac1011ebb5ce73739d3 there is a custom data map available on connections. Any release tracer that needed it could simply store it there.

**Comment by ngavinsir** [comment]
@jackc I see, so for example someone can save the passed context on TraceAcquireEnd in the TraceAcquireEndData.Conn.PgConn().CustomData() and access it again inside trace release from TraceReleaseData.Conn.PgConn().CustomData()

**Comment by jackc** [comment]
Thanks!

**Pull request merged**
