### PR TITLE
Fix pgconn cancel query through the PGBouncer

### LINKED ISSUE #1764: pgx doesn't cancel query correctly through pgbouncer
**Describe the bug**
https://github.com/jackc/pgx/pull/1621/commits/12b177f8a34d2c666304f3cc84fd8ca4b460da7a causes queries not being cancelled corretly through the PGBouncer. It's not sufficient to only write in the connection.

**To Reproduce**
Test is updated also to check cancellation of queries through the PGBouncer.

1. Run long query and cancel it
```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("PGX_TEST_PGBOUNCER_CONN_STRING"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())
        
        ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()
	
	err = conn.Query(ctx, "select pg_sleep(30)")
}
```
2. Check pg_stat_activity
```
select * from pg_stat_activity where state='active';
```

**Expected behavior**
Queries should be cancelled when using PGbouncer as it works with PostgreSQL directly.

**Actual behavior**
Queries remain active in pg_stat_activity

**Version**
 - Go: go1.21.2 darwin/amd64
 - PGBouncer: 1.20.1
 - PostgreSQL: PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
 - pgx: v5.4.3

### PR DESCRIPTION
**Pull request by levakin**
Closes #1764

### CODE REVIEW

**Comment by jackc** [comment]
As far as I can tell, the current behavior is still within acceptable behavior for PostgreSQL. The change this reverts fails on Windows. I'm not sure exactly why. @drakkan worked on this change. Perhaps they could elaborate.

But it is surprising that not reading could be a problem -- there are no bytes to read. The only reason the code originally read was to wait for the server to close the connection.

**Comment by levakin** [comment]
```
pgconn_test.go:2253: 
        	Error Trace:	D:\a\pgx\pgx\pgconn\pgconn_test.go:2253
        	Error:      	Received unexpected error:
        	            	read tcp [::1]:56732->[::1]:5432: wsarecv: An existing connection was forcibly closed by the remote host.
        	Test:       	TestConnCancelRequest
```
@drakkan network seems to work differently on windows. Any ideas why?

**Comment by drakkan** [comment]
Hi,

This change was made to fix test cases on Windows. I thought the error was related to the raw system calls used at the time, but I see this happening even now that we no longer have platform-specific code

**Comment by levakin** [comment]
hi, @jackc I've added handling of of this specific error. What do you think of it? Can you please run workflow again?

**Comment by levakin** [comment]
@jackc 

> The only reason the code originally read was to wait for the server to close the connection.

That's exactly the reason I want to revert this commit. 
My current understanding is that due to the usage of PGbouncer, the connection is not fast enough to deliver the instruction and `defer cancelConn.Close()` closes the connection than the instruction is delivered. And the query keeps running as a result.

Here's the pgbouncer log:
```
kpis-pgbouncer-shard1-1  | 2023-10-09 14:42:51.238 UTC [1] LOG S-0x5631ef4891d0: shard1/postgres@172.22.0.2:5432 new connection to server (from 172.22.0.6:33088)
kpis-pgbouncer-shard1-1  | 2023-10-09 14:42:54.005 UTC [1] LOG C-0x5631ef481e80: shard1/postgres@172.22.0.1:57294 closing because: client close request (age=345s)
kpis-pgbouncer-shard1-1  | 2023-10-09 14:42:54.005 UTC [1] LOG S-0x5631ef4891d0: shard1/postgres@172.22.0.2:5432 closing because: client disconnect while server was not ready (age=2s)
kpis-pgbouncer-shard1-1  | 2023-10-09 14:42:54.005 UTC [1] LOG C-0x5631ef481e80: (nodb)/(nouser)@172.22.0.1:38600 closing because: failed cancel request (age=0s)
kpis-pgbouncer-shard1-1  | 2023-10-09 14:42:54.506 UTC [1] LOG C-0x5631ef481e80: shard1/postgres@172.22.0.1:38606 login attempt: db=shard1 user=postgres tls=no
kpis-pgbouncer-shard1-1  | 2023-10-09 14:42:54.508 UTC [1] LOG S-0x5631ef4891d0: shard1/postgres@172.22.0.2:5432 new connection to server (from 172.22.0.6:33094)
```

**Comment by za-arthur** [comment]
FYI here is how Postgres libpq sends cancel request:
https://github.com/postgres/postgres/blob/REL_16_0/src/interfaces/libpq/fe-connect.c#L4946-L4960

Looks like it waits for a response from a server and ignores all errors. AFAIK EINTR can be ignored by pgx since go runtime handles it.

**Comment by timyakjuju** [comment]
not a bad idea

**Comment by jackc** [comment]
LGTM.

**Pull request merged**
