### PR TITLE
Load user-defined array type oids.

### PR DESCRIPTION
**Pull request by damour**
Fix https://github.com/jackc/pgx/issues/580

### CODE REVIEW

**Comment by jackc** [comment]
Is it possible to do what you want without loading array types for all tables?

We previously had a problem where it was extremely slow to connect to databases with large numbers of tables: #140. This change would return to the behavior before that was fixed.

**Comment by damour** [comment]
Sorry for late response I was on vacation.
Yes, I think it's possible something like this:

```
select t.oid,
	case when nsp.nspname in ('pg_catalog', 'public') then t.typname
		else nsp.nspname||'.'||t.typname
	end
FROM
  pg_type t
LEFT JOIN pg_type base_type
 ON t.typelem = base_type.oid
LEFT JOIN pg_class base_cls
 ON base_type.typrelid = base_cls.oid
LEFT JOIN pg_namespace nsp
 ON t.typnamespace = nsp.oid
LEFT JOIN pg_class cls
 ON t.typrelid = cls.oid
WHERE (
  t.typtype IN ( 'b','p','r','e','c' ) and (
      base_type.oid is null or base_type.typtype IN ( 'b','p','r','c' )
  )
  and (cls.oid is null or cls.relkind = 'c') 
  and (base_cls.oid is null or base_cls.relkind = 'c') 
)
```
If this is appropriate solution I can update MR.

**Comment by jackc** [comment]
I think this would work.

**Comment by damour** [comment]
Done, PTAL.

**Comment by jackc** [comment]
Thanks. LGTM.

**Pull request merged**
