### PR TITLE
Fix doc replicated words

### PR DESCRIPTION
**Pull request by smiletrl**
- One small doc fix
- Pgx pool QueryRow misses release https://github.com/jackc/pgx/blob/master/pgxpool/pool.go#L456

### CODE REVIEW

**Comment by jackc** [comment]
The connection can't be released until the row is scanned and the release happens when it is scanned. See #1050 for more discussion of the same issue.

**Comment by smiletrl** [comment]
ah, I see. Could you help describe the race condition if release happens before scan?

**Comment by smiletrl** [comment]
Right now, `QueryRow` must be chained by Scan(), otherwise it will eat all available connections. In this case, I feel `QueryRow` should be removed, but replaced with something like `QueryRowScan`, which will always release the connection.

Is this struct `Pool` is implementing some interface, which must include `QueryRow`?

**Comment by jackc** [comment]
Why would `QueryRow` be called without also calling `Scan`?

**Comment by smiletrl** [comment]
ah, personally I don't have a specific case without calling `Scan`. Just feel it doesn't look right that if one function must be chained by another one, otherwise it could break the application, like bug reported at https://github.com/jackc/pgx/pull/1050.

**Comment by smiletrl** [comment]
This release is removed now^ This pr only fixes that doc.

**Pull request merged**
