### PR TITLE
pgtype.Array: add MarshalJSON

### PR DESCRIPTION
**Pull request by carlmjohnson**
Refs #1509

### CODE REVIEW

**Comment by jackc** [comment]
Not sure how I feel about this. Any non-standard dimensions won't survive a JSON marshalling. OTOH, this is a more convenient representation for the typical use case. 🤔

**Comment by carlmjohnson** [comment]
When you say it won't surive marshalling, do you mean just because there's no UnmarshalJSON method yet or because there's no equivalent for the offset thing?

**Comment by jackc** [comment]
No equivalent for the offset. i.e. marshalling to JSON is a lossy operation.

**Comment by carlmjohnson** [comment]
Closing following discussion and changes to SQLC.

**Pull request closed without merging**
